// Extra per-animal content for the redesigned checker page (English).
// Traditional cultural associations, for entertainment and reflection only.
const CHECKER_EXTRA = {
  Rat: { kanji:"鼠", yin:"Yang",
    personality:["Quick-witted and resourceful","Charming and sociable","Observant of opportunities","Adaptable under pressure","Careful with security and money"],
    love:["Loyal once trust is built","Enjoys lively conversation","Protective of loved ones","Can be guarded at first","Needs honesty and reassurance"],
    career:["Strategic and sharp-minded","Strong at research and trading","Good at spotting trends","Thrives in business and writing","Prefers clever, flexible work"],
    directions:"West, Northwest, North", months:"January, June, September" },
  Ox: { kanji:"牛", yin:"Yin",
    personality:["Reliable and honest","Patient and determined","Practical and grounded","Strong sense of duty","Slow to change, hard to move"],
    love:["Steady and devoted","Shows love through actions","Values stability and tradition","Slow to open up","Needs a patient partner"],
    career:["Hardworking and disciplined","Excels in long-term projects","Dependable team member","Strong in farming, finance, building","Builds success step by step"],
    directions:"North, Northeast, South", months:"February, May, August" },
  Tiger: { kanji:"虎", yin:"Yang",
    personality:["Brave and confident","Passionate and competitive","Natural risk-taker","Charismatic presence","Can be impulsive"],
    love:["Intense and romantic","Loves adventure together","Fiercely loyal","Needs freedom and respect","Dislikes being controlled"],
    career:["Born to lead and inspire","Thrives on challenge","Bold decision-maker","Good in sports, law, entrepreneurship","Needs room to act independently"],
    directions:"East, South, Southeast", months:"March, July, November" },
  Rabbit: { kanji:"兔", yin:"Yin",
    personality:["Gentle and thoughtful","Diplomatic and kind","Artistic and refined","Cautious by nature","Seeks harmony"],
    love:["Caring and affectionate","Creates a warm home","Avoids conflict","Sensitive to criticism","Needs calm and security"],
    career:["Tactful negotiator","Good with design and the arts","Detail-oriented and careful","Works well in teams","Thrives in peaceful settings"],
    directions:"East, Southeast, South", months:"January, April, October" },
  Dragon: { kanji:"龍", yin:"Yang",
    personality:["Bold and charismatic","Ambitious and energetic","Confident and generous","Natural center of attention","Can be proud or impatient"],
    love:["Passionate and magnetic","Loves grand gestures","Expects loyalty","Needs a partner with confidence","Dislikes feeling restricted"],
    career:["Visionary leader","Thinks big","Excels in business and creative fields","Inspires others","Takes charge of new ventures"],
    directions:"East, Southeast, West", months:"March, June, December" },
  Snake: { kanji:"蛇", yin:"Yin",
    personality:["Wise and intuitive","Calm and deeply private","Elegant and observant","Determined in pursuit of goals","Slow to trust"],
    love:["Deeply loyal and intense","Enjoys meaningful connection","Can be possessive","Values intellect and depth","Needs trust and honesty"],
    career:["Analytical and strategic","Excels in research and finance","Works well alone","Strong in planning","Prefers thoughtful, quality work"],
    directions:"Southwest, West, South", months:"April, August, September" },
  Horse: { kanji:"馬", yin:"Yang",
    personality:["Energetic and optimistic","Independent and confident","Loves freedom and adventure","Charismatic and outgoing","Quick thinker and adaptable"],
    love:["Passionate and romantic","Likes excitement and fun","Values honesty and freedom","Attracts many admirers","Needs a supportive partner"],
    career:["Ambitious and hardworking","Great at leadership","Good communicator","Excels in creative industries","Enjoys variety and new challenges"],
    directions:"South, Southeast, Southwest", months:"March, June, September" },
  Goat: { kanji:"羊", yin:"Yin",
    personality:["Gentle and creative","Compassionate and kind","Artistic and imaginative","Easygoing but sensitive","Prefers peace over conflict"],
    love:["Tender and romantic","Devoted to family","Needs emotional security","Can be indecisive","Values harmony at home"],
    career:["Creative and intuitive","Shines in arts, design, caring work","Works best in supportive teams","Dislikes rigid pressure","Brings warmth to any workplace"],
    directions:"South, Southeast, East", months:"February, July, October" },
  Monkey: { kanji:"猴", yin:"Yang",
    personality:["Clever and curious","Playful and witty","Inventive problem-solver","Quick to learn","Can get restless"],
    love:["Fun and flirtatious","Loves laughter and variety","Needs mental stimulation","Can fear commitment","Values a playful partner"],
    career:["Innovative and versatile","Great at sales and communication","Thrives in technology and media","Learns new skills fast","Enjoys solving puzzles"],
    directions:"West, Northwest, North", months:"February, August, December" },
  Rooster: { kanji:"雞", yin:"Yin",
    personality:["Hardworking and observant","Confident and organized","Honest and direct","Takes pride in appearance","Perfectionist streak"],
    love:["Loyal and devoted","Shows care through effort","Direct about feelings","Can be critical","Needs appreciation"],
    career:["Detail-focused and diligent","Excels in management and service","Strong planner","Good in finance and media","Takes pride in quality"],
    directions:"West, Southwest, Northwest", months:"May, September, November" },
  Dog: { kanji:"狗", yin:"Yang",
    personality:["Loyal and honest","Fair-minded and responsible","Protective of friends","Cautious and thoughtful","Can worry too much"],
    love:["Faithful and sincere","Values trust above all","Deeply protective","Slow but steady in love","Needs loyalty in return"],
    career:["Trustworthy and ethical","Excels in service, law, teaching","Strong team player","Reliable under pressure","Driven by purpose"],
    directions:"East, South, Southeast", months:"March, July, October" },
  Pig: { kanji:"豬", yin:"Yin",
    personality:["Generous and warm-hearted","Easygoing and sincere","Enjoys comfort and good company","Patient and diligent","Can be too trusting"],
    love:["Affectionate and giving","Loves cozy time together","Loyal and tolerant","Avoids conflict","Needs a sincere partner"],
    career:["Dedicated and hardworking","Great with people and hospitality","Generous team supporter","Good in food, care, and creative work","Enjoys a pleasant workplace"],
    directions:"East, Southeast, North", months:"January, May, August" }
};
